FROM maven:3.9.5-sapmachine-21
# aqui tambien expecifico la version del jdk 21 que tenemos



# nombres: 
#     samuel david ospina de avila
#     maria alejandra perez hernandez
#     rafael barragan acevedo